FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY sensors/trajectory.py sensors/control_server.py sensors/gps_sim.py ./
EXPOSE 8080
CMD ["python", "gps_sim.py"]
